# Generated by Django 3.0.5 on 2020-05-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to='technician_api.Student'),
        ),
    ]
