# Generated by Django 3.0.5 on 2020-05-29 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technician_api', '0002_auto_20200512_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='equipment'),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='ref',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Missing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=32)),
                ('reason', models.CharField(max_length=64, null=True)),
                ('equipment_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician_api.Equipments')),
                ('group_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician_api.Group')),
                ('project_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician_api.Project')),
            ],
        ),
    ]
